name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * 4'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: test bash verify.sh
        run: ./test.sh | ./verify.sh -t verify-cli-bash
        working-directory: bash

      - name: failure returns non-zero exit code
        run: '! (./verify.sh -t failing-test -d echo <<< "input")'
        working-directory: bash
